taxi_rides_ny:
  target: dev
  outputs:
    # DuckDB Development profile
    dev:
      type: duckdb
      path: /home/ubuntu/DataEngineering_Ny_Taxi_Data_ETL_Pipeline/module4/taxi_rides_ny/taxi_rides_ny.duckdb
      schema: prod
      threads: 1
      extensions:
        - parquet
      settings:
        memory_limit: '4GB'
        preserve_insertion_order: false

    # DuckDB Production profile
    prod:
      type: duckdb
      path: /home/ubuntu/DataEngineering_Ny_Taxi_Data_ETL_Pipeline/module4/taxi_rides_ny/taxi_rides_ny.duckdb
      schema: prod
      threads: 1 # 2 
      extensions:
        - parquet
      settings:
        memory_limit: '1GB'
        #temp_directory: '/tmp/duckdb_temp'  # remove for fct_trips # Move the spill-to-disk location
        preserve_insertion_order: false
        #max_temp_directory_size: '30GB' # remove for fct_trips

  target: dev
